/*
 * This is sample code generated by rpcgen and modified by Palak Shah
 * This code has borrowed some functions and code from hw2.c for local FS given along with hw2.pdf
 * This code is submitted as hw2 for Distributed Computing
 */

#include "hw2.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <string.h>
#include <dirent.h>
#include <time.h>

static int res;
static char* data;
static long fsize;
long lookup(char *filename); 
file* listfiles(void); 

outparams * fileprog_1_svc(inparams *in, struct svc_req *rqstp) {
	//static outparams  result;
	static outparams *r;
	static file *listout;
	time_t rawtime;
  	struct tm * tm;
	static int len; 

	r = (outparams *)malloc(sizeof(outparams));

	//initialize output parameters to avoid null pointer errors
	r->outfsize = 1;
	r->outdata= "hello";
	r->outlst.name = "palak";
	r->outlst.next = NULL;
	r->errcode = -87;

	//get local time
	time ( &rawtime );
  	tm = localtime ( &rawtime );

	//open file called server.log
	FILE *f;
	f = fopen("server.log", "a");
	if (f == NULL){
 		printf("Error opening file!\n");
    		exit(1);
	}
	
	//the following code is for running operations and printing results on server console
	//the code for saving in server.log file is included in this logic

	//if operation = cat
	if (strcmp(in->cmd, CAT) == 0) {
		printf("\n[%d/%d %d:%d:%d] %s %s %d\n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile, in->len);
		fprintf(f, "\n[%d/%d %d:%d:%d] %s %s %d\n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile, in->len);
		res = create(in->infile);
		r->errcode = res;
		if (res == 0) {
			if (in->len <= 0) {
				
			}
			else{
				data = malloc(in->len);
				fsize = readfile(data, in->len, in->infile);
				if (fsize < 0) {
					fprintf(f, "Error in opening:\n");					
					printf("Error in opening:\n");
				} else {
					r->outdata = data;
					fprintf(f,"%s\n", data);
					printf("%s\n", data);
				}
			}
		}else if(res == -1) {
			fprintf(f,"Error in opening %s\n", in->infile);
			printf("Error in opening %s\n", in->infile);
		} else {
			fprintf(f,"File %s has been created \n", in->infile);
			printf("File %s has been created \n", in->infile);
		}//inner loop ends here
	}//if loop ends here

	//if operation = find
	else if (strcmp(in->cmd, FIND) == 0) {
		printf("\n[%d/%d %d:%d:%d] %s %s \n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile);
		fprintf(f, "\n[%d/%d %d:%d:%d] %s %s \n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile);
		fsize = lookup(in->infile);
		r->outfsize = fsize;	
		if (fsize< 0) {
			fprintf(f,"Could not find %s\n", in->infile);
			printf("Could not find %s\n", in->infile);
		} else {
			
			fprintf(f, "File %s has %ld bytes\n", in->infile, fsize);
			printf("File %s has %ld bytes\n", in->infile, fsize);
		}	
	}

	//if operation = rm
	else if (strcmp(in->cmd, RM) == 0) {
		printf("\n[%d/%d %d:%d:%d] %s %s \n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile);
		fprintf(f, "\n[%d/%d %d:%d:%d] %s %s\n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile);
		res = delete(in->infile);
		r->errcode = res;
		if (res == 0) { 
			fprintf(f, "File %s has been deleted\n", in->infile);
			printf("File %s has been deleted\n", in->infile);
		} else if (res == -2) {
			fprintf(f,"File %s does not exist\n", in->infile);
			printf("File %s does not exist\n", in->infile);
		} else {
			fprintf(f,"Error in deleting %s\n", in->infile);
			printf("Error in deleting %s\n", in->infile);
		}
	}	
       
	//if operation = ls
	else if (strcmp(in->cmd, LS) == 0) {
		printf("\n[%d/%d %d:%d:%d] %s \n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd);
		fprintf(f, "\n[%d/%d %d:%d:%d] %s \n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd);
		printf("list command given\n");
		listout = listfiles();
		printf("list command taken\n");
		r->outlst = *listout;
		if (listout == NULL) {
			fprintf(f, "Error in listing:\n");
			printf("Error in listing:\n");
		} else {
			for (; listout != (file *) NULL; listout = listout->next) {
				fprintf(f,"%s\n", listout->name);				
				printf("%s\n", listout->name);
			}
		}
	}
       
	//if operation = write
       	else if (strcmp(in->cmd, WRITE) == 0) {
		printf("\n[%d/%d %d:%d:%d] %s %s %s\n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile, in->str);
		fprintf(f,"\n[%d/%d %d:%d:%d] %s %s %s\n", tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, in->cmd, in->infile, in->str);
		len = strlen(in->str);
               	fsize = writefile(in->str, len, in->infile);
		r->outfsize = fsize;
		if (fsize < 0) {
			fprintf(f,"Error in writing:\n");        
		       	printf("Error in writing:\n");
               	} else {
			fprintf(f, "%ld bytes of data were written to file %s\n", fsize, in->infile);
			printf("%ld bytes of data were written to file %s\n", fsize, in->infile);
               	}
       	}

	//if operation = exit
	else if (strcmp(in->cmd, "exit") == 0) {
		printf("exiting...\n");
		exit(0);
	}
	
	fclose(f);
	return r; 
	//return &result;
}//fileprog_1_svc ends here

/*the following functions have borrowed code from hx2.c for local filesystem given along with hw2*/


//function to look up a file in the FS
long lookup(char *filename) {
	int status;
	struct stat statbuf;

	if (stat(filename, &statbuf) == -1) {	
		return (long)-1;
	}
	
	return (long)statbuf.st_size;

}

//function to read the contents of a file
int readfile(char *data, int length, char *filename) {
	FILE *fp = fopen(filename, "r");
	if (fp == NULL) {
		return -1;
	}
	int size = fread(data, sizeof(char), length, fp);
	fclose(fp);
        return size;
}

//function to write data into a file
int writefile(char *data, int length, char *filename) {
	FILE *fp = fopen(filename, "w+");
	if (fp == NULL) {
		return -1;
	}
	int size = fwrite(data, sizeof(char), length, fp);
	fclose(fp);
	return size;
}

//function to create a file
int create(char *filename) {
	if (lookup(filename) > -1) {
		return 0;
	}
	FILE *fp = fopen(filename, "w+");
	if (fp == NULL) {
		return -1;
	}
	fclose(fp);
	return 1;
}

//function to delete a file
int delete(char *filename) {
	if (lookup(filename) < 0) {
		return -2;
	}
	return remove(filename);
}

//function to list files in the current directory
file *listfiles() {
	DIR *pdir;
	struct dirent *ent;
	file *tmp;
	static file *lst;

	pdir = opendir("."); /*assuming the simple file system is located in the current directory */
	if (pdir == NULL) {
		return NULL;
	}
	
	lst = (file *) NULL;
	while((ent = readdir(pdir)) != NULL) {
		tmp = (file *) malloc(sizeof(file));
		tmp->name = (char *) malloc(sizeof(ent->d_name)+1);
		strcpy (tmp->name, ent->d_name);
		tmp->next = lst;
		lst = tmp;
	}
	closedir(pdir);
	return lst;
}

